version: '3.7'
services:
  dalai:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /Users/user/Downloads/00_ai_Models/ggml-alpaca:/root/dalai/alpaca
      - /Users/user/Downloads/00_ai_Models/llama:/root/dalai/llama
